"""How the platform gets temporary, read-only access to a client AWS account.

Flow (AWS STS = Security Token Service):

  platform identity --AssumeRole(role ARN, ExternalId)--> STS
  STS --temporary keys (max 1 hour)--> platform
  platform --read-only calls with those keys--> client account

The temporary keys exist only in memory, inside the returned boto3 Session. They are
never written to disk, logs or the database.
"""

import re
import secrets
from dataclasses import dataclass
from typing import Any

import boto3
from botocore.config import Config

from app.core.config import Settings
from app.providers.aws.guard import (
    PLATFORM_OPERATIONS,
    assessment_operations,
    guarded_session,
)

# Retries with backoff for throttling; short timeouts so a scan never hangs.
CLIENT_CONFIG = Config(
    retries={"mode": "standard", "max_attempts": 5},
    connect_timeout=5,
    read_timeout=30,
    user_agent_extra="cloudsecura",
)

ACCOUNT_ID_PATTERN = re.compile(r"^\d{12}$", re.ASCII)
# AWS allows these characters in an ExternalId.
EXTERNAL_ID_PATTERN = re.compile(r"^[\w+=,.@:/-]{2,1224}$", re.ASCII)


@dataclass(frozen=True)
class AwsConnection:
    """What the platform stores about a client AWS connection. Nothing secret
    that grants access on its own: without the platform identity, these are inert."""

    account_id: str
    external_id: str
    role_name: str

    def __post_init__(self) -> None:
        if not ACCOUNT_ID_PATTERN.fullmatch(self.account_id):
            raise ValueError("AWS account ID must be exactly 12 digits")
        if not EXTERNAL_ID_PATTERN.fullmatch(self.external_id):
            raise ValueError("ExternalId has invalid characters or length")

    @property
    def role_arn(self) -> str:
        # Built from the account ID, never pasted, so the target account is explicit.
        # Commercial AWS partition only; GovCloud and China are out of scope.
        return f"arn:aws:iam::{self.account_id}:role/{self.role_name}"


def generate_external_id(consultancy_name: str) -> str:
    """A unique, unguessable ExternalId for one client connection. Generated by the
    platform (never chosen by the client), as AWS recommends."""
    return f"{consultancy_name.lower()}-{secrets.token_urlsafe(24)}"


def platform_session(settings: Settings) -> boto3.Session:
    """The platform's own identity, from boto3's standard credential sources.
    Guarded so it can only call sts:GetCallerIdentity and sts:AssumeRole."""
    return guarded_session(PLATFORM_OPERATIONS, region_name=settings.aws_region)


def _session_name(consultancy_name: str) -> str:
    # Visible in the client's CloudTrail: tells them exactly who made each call.
    return f"{consultancy_name}-assessment-{secrets.token_hex(4)}"[:64]


def assume_assessment_role(
    connection: AwsConnection, settings: Settings, platform: Any | None = None
) -> boto3.Session:
    """Return a guarded boto3 Session holding temporary credentials for the client's
    read-only role. Raises botocore errors on failure (see errors.describe_aws_error)."""
    platform = platform or platform_session(settings)
    sts = platform.client("sts", config=CLIENT_CONFIG)
    response = sts.assume_role(
        RoleArn=connection.role_arn,
        RoleSessionName=_session_name(settings.consultancy_name),
        ExternalId=connection.external_id,
        DurationSeconds=settings.aws_session_duration_seconds,
    )
    credentials = response["Credentials"]
    return guarded_session(
        assessment_operations(),
        aws_access_key_id=credentials["AccessKeyId"],
        aws_secret_access_key=credentials["SecretAccessKey"],
        aws_session_token=credentials["SessionToken"],
        region_name=settings.aws_region,
    )
