"""Least-privilege cloud permissions, generated from the code (ADR 0025).

The read-only guards already know exactly which permissions the enabled checks
need (`assessment_permissions()` for AWS and Azure). This module turns that same
list into what clients grant, so the two can never drift apart:

- AWS: the "AssessmentReadOnly" policy in infra/aws/client-onboarding-role.yaml
  (between the GENERATED markers) and infra/aws/least-privilege-policy.json;
- Azure: a custom role, infra/azure/assessment-role.json, and the role definition
  in each client's onboarding steps.

    python -m app.policies          rewrite the files above
    python -m app.policies --check  exit 1 if any of them is out of date (tests do this)
"""

import argparse
import json
import os
import shlex
import sys
from pathlib import Path
from typing import Any

from app.core.config import Settings
from app.providers.aws import guard as aws_guard
from app.providers.azure import guard as azure_guard

INFRA = Path(__file__).resolve().parents[2] / "infra"
if not INFRA.is_dir():  # inside the container the repository's infra/ is mounted at /infra
    INFRA = Path("/infra")
# `dev.ps1 policies` mounts a writable copy elsewhere (the usual mount is read-only).
INFRA = Path(os.environ.get("POLICIES_INFRA_DIR", INFRA))

AWS_TEMPLATE = INFRA / "aws" / "client-onboarding-role.yaml"
AWS_POLICY = INFRA / "aws" / "least-privilege-policy.json"
AZURE_ROLE = INFRA / "azure" / "assessment-role.json"

BEGIN = "# BEGIN GENERATED by `python -m app.policies` (do not edit by hand)"
END = "# END GENERATED"

# Permissions the AWS connector needs beyond the checks: listing the enabled regions.
# (sts:GetCallerIdentity needs no permission.)
AWS_CONNECTOR_PERMISSIONS = frozenset({"ec2:DescribeRegions"})


def aws_actions() -> list[str]:
    actions = sorted(aws_guard.assessment_permissions() | AWS_CONNECTOR_PERMISSIONS)
    for action in actions:  # defence in depth: the guard already refuses anything else
        name = action.split(":", 1)[1]
        if not name.startswith(aws_guard.READ_PREFIXES) and (
            action not in aws_guard.READ_ONLY_EXCEPTIONS
        ):
            raise ValueError(f"not a read permission: {action}")
    return actions


def aws_policy() -> dict[str, Any]:
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "ExactlyWhatTheChecksRead",
                "Effect": "Allow",
                "Action": aws_actions(),
                "Resource": "*",
            }
        ],
    }


def azure_actions() -> list[str]:
    return sorted(azure_guard.assessment_permissions(), key=str.lower)


def azure_role_name(consultancy: str) -> str:
    return f"{consultancy} Security Assessment (read-only)"


def azure_role(consultancy: str, subscription_id: str) -> dict[str, Any]:
    """An Azure custom role definition, in the format `az role definition create`
    accepts. Read actions only: no data actions, nothing that changes anything."""
    return {
        "Name": azure_role_name(consultancy),
        "IsCustom": True,
        "Description": (
            "Read-only security assessment: reads the configuration the checks need. "
            "No data access, no changes."
        ),
        "Actions": azure_actions(),
        "NotActions": [],
        "DataActions": [],
        "NotDataActions": [],
        "AssignableScopes": [f"/subscriptions/{subscription_id}"],
    }


def azure_role_commands(consultancy: str, subscription_id: str, app_id: str) -> list[str]:
    """Azure Cloud Shell commands: create the custom role, then assign it to the app."""
    definition = json.dumps(azure_role(consultancy, subscription_id), separators=(",", ":"))
    scope = f"/subscriptions/{subscription_id}"
    # shlex.quote: the consultancy name is configuration, but quote it all the same.
    return [
        f"az role definition create --role-definition {shlex.quote(definition)}",
        f"az role assignment create --assignee {app_id} "
        f"--role {shlex.quote(azure_role_name(consultancy))} --scope {scope}",
    ]


def azure_builtin_role_commands(subscription_id: str, app_id: str) -> list[str]:
    """Fallback: Azure's built-in read-only roles (broader than the checks need)."""
    scope = f"/subscriptions/{subscription_id}"
    return [
        f'az role assignment create --assignee {app_id} --role "{role}" --scope {scope}'
        for role in ("Reader", "Security Reader")
    ]


def _json(document: dict[str, Any]) -> str:
    return json.dumps(document, indent=2) + "\n"


def _template_with_actions(template: str) -> str:
    start, end = template.index(BEGIN), template.index(END)
    line_start = template.rfind("\n", 0, start) + 1
    indent = template[line_start:start]
    block = "".join(f"{indent}- {action}\n" for action in aws_actions())
    return template[: start + len(BEGIN)] + "\n" + block + indent + template[end:]


def expected_files() -> dict[Path, str]:
    # Files in the repository use the default name, like the AWS template's default
    # role name; each client's onboarding steps use the configured one.
    consultancy = Settings.model_fields["consultancy_name"].default
    return {
        AWS_TEMPLATE: _template_with_actions(AWS_TEMPLATE.read_text(encoding="utf-8")),
        AWS_POLICY: _json(aws_policy()),
        AZURE_ROLE: _json(azure_role(consultancy, "<subscription-id>")),
    }


def outdated() -> list[Path]:
    return [
        path
        for path, content in expected_files().items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m app.policies", description=__doc__)
    parser.add_argument("--check", action="store_true", help="only check, do not write")
    args = parser.parse_args(argv)
    if args.check:
        stale = outdated()
        for path in stale:
            print(f"out of date: {path}")
        return 1 if stale else 0
    for path, content in expected_files().items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
