"""Finding review layer and assessment finalization (M12).

Review events and finalizations are history: a trigger refuses UPDATE (the same
function that protects stored scan results). Rows are removed only with their
assessment.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 00:37:23.040942
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finding_review_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=254), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "confirmed",
                "false_positive",
                "accepted_risk",
                name="review_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity_override",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "informational",
                name="severity_override",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("justification", sa.String(length=2000), nullable=True),
        sa.Column(
            "previous_status",
            sa.Enum(
                "open",
                "confirmed",
                "false_positive",
                "accepted_risk",
                name="previous_review_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "previous_severity_override",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "informational",
                name="previous_severity_override",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id", "client_id"],
            ["assessments.id", "assessments.client_id"],
            name=op.f("fk_finding_review_events_assessment_id_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_review_events")),
    )
    op.create_index(
        "ix_finding_review_events_finding",
        "finding_review_events",
        ["assessment_id", "fingerprint", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "finding_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "confirmed",
                "false_positive",
                "accepted_risk",
                name="review_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity_override",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "informational",
                name="severity_override",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("justification", sa.String(length=2000), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.String(length=254), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status NOT IN ('false_positive', 'accepted_risk') AND severity_override IS NULL)"
            " OR length(trim(coalesce(justification, ''))) >= 10",
            name=op.f("ck_finding_reviews_decision_justified"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id", "client_id"],
            ["assessments.id", "assessments.client_id"],
            name=op.f("fk_finding_reviews_assessment_id_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_reviews")),
        sa.UniqueConstraint(
            "assessment_id",
            "fingerprint",
            name=op.f("uq_finding_reviews_assessment_id_fingerprint"),
        ),
    )
    op.create_table(
        "assessment_finalizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("scan_run_id", sa.Uuid(), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("finalized_by", sa.String(length=254), nullable=False),
        sa.Column(
            "report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("report_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "length(report_sha256) = 64",
            name=op.f("ck_assessment_finalizations_final_report_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id", "client_id"],
            ["assessments.id", "assessments.client_id"],
            name=op.f("fk_assessment_finalizations_assessment_id_client_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scan_run_id", "client_id"],
            ["scan_runs.id", "scan_runs.client_id"],
            name=op.f("fk_assessment_finalizations_scan_run_id_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_finalizations")),
    )
    op.create_index(
        "ix_assessment_finalizations_assessment",
        "assessment_finalizations",
        ["assessment_id", "finalized_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Written by hand: review history and finalized reports are never modified.
    for table in ("finding_review_events", "assessment_finalizations"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION refuse_update_of_stored_results()"
        )


def downgrade() -> None:
    for table in ("finding_review_events", "assessment_finalizations"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_assessment_finalizations_assessment", table_name="assessment_finalizations")
    op.drop_table("assessment_finalizations")
    op.drop_table("finding_reviews")
    op.drop_index("ix_finding_review_events_finding", table_name="finding_review_events")
    op.drop_table("finding_review_events")
    # ### end Alembic commands ###
